---
title: "Untitled"
author: "YAN LI"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


```

## R Markdown
```{r}

		
		knitr::opts_chunk$set(
		echo = TRUE,
		eval = TRUE,
		message = FALSE,
		warning = FALSE, 
		out.height = "100%",
		out.width = "100%",
		paged.print=TRUE, 
		fig.show = "hold", 
		cache = T
		)		  
					
title: "POMALIDOMIDE BE STUDY PK SUMMARY"
author: "yanli"
date: "`r Sys.time()`"
output:
  html_document:
    theme: cosmo
    highlight: tango
    anchor_sections: yes
    toc: yes
    toc_float: yes
    number_section: yes
    code_folding: hide
    code_download: yes
				
 

    
    
```




```{r}


library(Rcpp) 
library(eoffice)
library(usethis) 
library(ggforce)
library(widyr)
library(corrr)
library(tictoc)
library(plotly)
library(lubridate)
library(stringr)
library(ggthemes)
library(extrafont)
library(AER)
library(tidyxl)
library(ggstatsplot)
library(ggcorrplot)
library(ggside)
library(stringi)
library(progressr)
library(skimr)
library(knitr)
library(usemodels)
library(tidymodels)
library(readr)
library(readxl)
library(ggplot2)  
library(tidyr) 
library(dplyr)
library(purrr)
library(broom)
library(tidylog)
library(tidyverse)
library(janitor)
library(haven)
library(data.table)
library(patchwork)
library(furrr) 
library(lme4)
library(broom.mixed)
library(rsample)
library(lattice)
library(rr2)
library(kableExtra)
library(rlang)
 
 

```

